"""Initial migration

Revision ID: d7a91ad30478
Revises: 
Create Date: 2025-05-26 12:37:26.750396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7a91ad30478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(100), nullable=False),
    sa.Column('last_name', sa.String(100), nullable=False),
    sa.Column('email', sa.String(255), unique=True, nullable=False),
    sa.Column('password_hash', sa.String(255), nullable=False),
    sa.Column('date_of_birth', sa.Date()),
    sa.Column('job_position', sa.String(100)),
    sa.Column('work_experience', sa.Integer()),
    sa.Column('last_login', sa.DateTime(), default=sa.func.current_timestamp()),
    sa.Column('is_active', sa.Boolean(), default=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text())),
    sa.Column('created_at', sa.DateTime(), default=sa.func.current_timestamp()),
    sa.Column('updated_at', sa.DateTime(), default=sa.func.current_timestamp(), onupdate=sa.func.current_timestamp()),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('link', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('direction', sa.TEXT(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
